version: "3.3"
services:
  farmer:
    container_name: farmer
    build:
      context: .
      dockerfile: docker/farmer.dockerfile
    volumes:
      - ./testing/farmer:/etc/grlx/farmer
      - .:/app
      - go-modules:/go/pkg/mod
    image: grlx/farmer:latest
    restart: unless-stopped
    ports:
      - "4443:4443"
      - "5405:5405"

  sprout_a:
    image: grlx/sprout:latest
    build:
      context: .
      dockerfile: docker/sprout.dockerfile
    volumes:
      - ./testing/sprout_a:/etc/grlx/sprout
      - .:/app
      - go-modules:/go/pkg/mod
    depends_on: 
      - farmer
  sprout_b:
    volumes:
      - ./testing/sprout_b:/etc/grlx/sprout
    image: grlx/sprout:latest
    depends_on: 
      - farmer
  sprout_c:
    volumes:
      - ./testing/sprout_c:/etc/grlx/sprout
    image: grlx/sprout:latest
    depends_on: 
      - farmer
  sprout_d:
    volumes:
      - ./testing/sprout_d:/etc/grlx/sprout
    image: grlx/sprout:latest
    depends_on: 
      - farmer
  sprout_e:
    volumes:
      - ./testing/sprout_e:/etc/grlx/sprout
    image: grlx/sprout:latest
    depends_on: 
      - farmer
  sprout_f:
    volumes:
      - ./testing/sprout_f:/etc/grlx/sprout
    image: grlx/sprout:latest
    depends_on: 
      - farmer
volumes:
  go-modules:
